[package]
name = "rust_maze"
version = "0.1.0"
authors = ["rtpike <impressive.rtpike@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.9.1"
rand = "0.8.3"
petgraph = "0.5.1"